name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./frontend

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "npm"
                  cache-dependency-path: ./package-lock.json

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install node dependencies
              run: npm ci --no-progress --prefer-offline

            - name: Install latest Ionic CLI
              run: npm install -g @ionic/cli

            - name: Install Angular CLI
              run: npm install -D @angular/cli

            - name: Install Capacitor (if required)
              run: npm install @capacitor/core @capacitor/cli

            - name: Verify ionic.config.json
              run: cat ionic.config.json # Debugging step

            - name: Build application
              run: ionic build --prod

            - name: Run unit tests
              run: npx ng test --watch=false --browsers=ChromeHeadless --no-progress
