name: CI Pipeline
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "npm"
                  cache-dependency-path: ./package-lock.json

            - name: Install root dependencies
              run: npm ci --no-progress --prefer-offline

            - name: Install frontend dependencies
              working-directory: ./frontend
              run: npm install --no-progress

            - name: Build application
              working-directory: ./frontend
              run: npx ng build --configuration=production

            - name: Install Lighthouse CI
              run: npm install -g @lhci/cli

            - name: Start ng serve in background
              working-directory: ./frontend
              run: |
                  nohup npx ng serve --disable-host-check --port 8100 &

            - name: Wait for ng serve to start
              run: npx wait-on http://localhost:8100/tabs/tab1

            - name: Run Lighthouse tests
              run: |
                  npx lhci autorun \
                    --collect.numberOfRuns=2 \
                    --upload.target=temporary-public-storage \
                    --collect.url="http://localhost:8100/tabs/tab1" \
                    --collect.url="http://localhost:8100/tabs/tab2" \
                    --collect.url="http://localhost:8100/tabs/tab3" \
                    --collect.url="http://localhost:8100/tabs/tab4" \
                    --collect.url="http://localhost:8100/tabs/tab5"

            - name: Run Jasmine unit tests
              working-directory: ./frontend
              run: npx ng test --watch=false --browsers=ChromeHeadless --no-progress
